// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouTennis.Core.Context;

namespace YouTennis.Core.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20190516073615_Identity")]
    partial class Identity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("YouTennis.Base.Model.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("YouTennis.Base.Model.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int>("ClubId");

                    b.Property<decimal>("HourPrice");

                    b.Property<string>("Image");

                    b.Property<string>("Street");

                    b.Property<string>("StreetNumber");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Court");
                });

            modelBuilder.Entity("YouTennis.Base.Model.OpeningHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("ClosingTime");

                    b.Property<int>("CourtId");

                    b.Property<int>("DayId");

                    b.Property<TimeSpan>("OpeningTime");

                    b.HasKey("Id");

                    b.ToTable("OpeningHours");
                });
#pragma warning restore 612, 618
        }
    }
}
